services:
  blogpostdb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - blognet

  blogpostapp:
    build: .
    depends_on:
      - blogpostdb
    environment:
      DB_HOST: blogpostdb
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: blogpostdb
    ports:
      - 8070:8080
    networks:
      - blognet

volumes:
  db-data:

networks:
  blognet:
    driver: bridge
